# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  
  paths:
    exclude:
      - README.md  

pool:
  name: Default 

steps:
- script: |
    ansible-playbook test.yml --extra-vars "@fortigate_credentials.yml"
  displayName: 'Run Ansible Playbook'

