---
- name: Configure address and address group on FortiGate firewall
  hosts: localhost
  gather_facts: no
  vars:
    address_details:
      - name: "testyash1"
        subnet: "1.1.2.7/32"
      - name: "testyash2"
        subnet: "1.1.2.8/32"
      - name: "testyash3"
        subnet: "1.1.2.9/32"
      - name: "testyash4"
        subnet: "1.1.2.10/32"
      - name: "testyash5"
        subnet: "1.1.2.11/32"
    firewall_ip: "10.255.255.65"
    firewall_user: "yash"
    firewall_password: "Lim"
    address_group_name: "ytest"
    comment_string: "changesfordemo"

  tasks:
    - name: Ping the firewall to check reachability
      command: ping -c 4 {{ firewall_ip }}
      ignore_errors: yes
      register: ping_result
      changed_when: false

    - name: Debug whether the host is up or down
      debug:
        msg: "Host is up, good to go"
      when: ping_result.rc == 0

    - name: Debug whether the host is up or down
      debug:
        msg: "Host is down"
      when: ping_result.rc != 0

    - name: SSH to FortiGate and configure addresses
      expect:
        command: ssh "{{ firewall_user }}@{{ firewall_ip }}"
        responses:
          (?i)password: "{{ firewall_password }}"
          ".*#": |
            config vdom
            edit root
            config firewall address
            {% for detail in address_details %}
            edit {{ detail.name }}
            set subnet {{ detail.subnet }}
            set comment {{ comment_string }}
            next
            {% endfor %}
            end
            config firewall addrgrp
            edit {{ address_group_name }}
            {% for detail in address_details %}
            append member {{ detail.name }}
            set comment {{ comment_string }}
            {% endfor %}
            end
            exit
      when: ping_result.rc == 0
