---
- name: Configure FortiGate Address and Address Group
  hosts: localhost
  gather_facts: no
  vars:
    firewall_ip: "192.168.1.7"
    username: "admin"
    password: "2002"
    new_address_name: "ytest"
    new_address_subnet: "192.168.2.0/24"
    existing_group_name: "Test"
    comment_string: "This is a comment for automation."

  tasks:
    - name: Run Expect script
      command: >
        expect -c "
          spawn ssh {{ username }}@{{ firewall_ip }}
          expect \"password:\"
          send \"{{ password }}\\r\"
          expect \"#\"
          send \"config firewall address\\r\"
          expect \"(address)\"
          send \"edit {{ new_address_name }}\\r\"
          expect \"(New_Address)\"
          send \"set subnet {{ new_address_subnet }}\\r\"
          send \"set comment \\\"{{ comment_string }}\\\"\\r\"
          send \"next\\r\"
          send \"end\\r\"
          expect \"#\"
          send \"config firewall addrgrp\\r\"
          expect \"(addrgrp)\"
          send \"edit {{ existing_group_name }}\\r\"
          expect \"(Existing_Address_Group)\"
          send \"append member {{ new_address_name }}\\r\"
          send \"set comment \\\"{{ comment_string }}\\\"\\r\"
          send \"next\\r\"
          send \"end\\r\"
          expect \"#\"
          send \"exit\\r\"
          expect eof
        "
