---
- name: Configure FortiGate firewall
  hosts: fortigate
  gather_facts: no
  vars:
    fortigate_user: "your_username"
    fortigate_ip: "your_fortigate_ip"
    fortigate_password: "your_password"
    ipsec_phase1_interface:
      name: "Netskope POP1"
      interface: "CROWN_INTERNET(CROWNCASTLE_ISP)"
      peertype: "any"
      net_device: "disable"
      proposal: ["aes128-sha256", "aes256-sha256", "aes128-sha1", "aes256-sha1"]
      localid: "FareportalLI"
      dpd: "on-idle"
      dhgrp: 2
      keylife: 86400
      remote_gw: "115.113.51.138"
      psksecret: "##@#d4m@##@#d4m@"
    ipsec_phase2_interfaces:
      - name: "Netskope POP1"
        proposal: ["aes128-shat", "aes256-sha1", "aes128gcm", "aes256gcm"]
        dhgrp: 2
        keylifeseconds: 43200
        auto_negotiate: "enable"
        src_subnet:
          - "0.0.0.0/0"
        dst_subnet:
          - "0.0.0.0/0"
      - name: "Netskope POP1"
        proposal: ["aes128-shat", "aes256-sha1", "aes128gcm", "aes256gcm"]
        dhgrp: 2
        keylifeseconds: 43200
        auto_negotiate: "enable"
        src_subnet:
          - "192.168.1.0/24"
        dst_subnet:
          - "172.16.0.0/16"

  tasks:
    - name: SSH to FortiGate and configure IPsec phase1 interface
      expect:
        command: ssh "{{ fortigate_user }}@{{ fortigate_ip }}"
        responses:
          (?i)password: "{{ fortigate_password }}"
          ".*#": |
            config vpn ipsec phase1-interface
            edit "{{ ipsec_phase1_interface.name }}"
            set interface "{{ ipsec_phase1_interface.interface }}"
            set peertype "{{ ipsec_phase1_interface.peertype }}"
            set net-device "{{ ipsec_phase1_interface.net_device }}"
            set proposal "{{ ipsec_phase1_interface.proposal | join(' ') }}"
            set localid "{{ ipsec_phase1_interface.localid }}"
            set dpd "{{ ipsec_phase1_interface.dpd }}"
            set dhgrp "{{ ipsec_phase1_interface.dhgrp }}"
            set keylife "{{ ipsec_phase1_interface.keylife }}"
            set remote-gw "{{ ipsec_phase1_interface.remote_gw }}"
            set psksecret "{{ ipsec_phase1_interface.psksecret }}"
            next
            end
            exit

    - name: SSH to FortiGate and configure IPsec phase2 interfaces
      expect:
        command: ssh "{{ fortigate_user }}@{{ fortigate_ip }}"
        responses:
          (?i)password: "{{ fortigate_password }}"
          ".*#": |
            {% for interface in ipsec_phase2_interfaces %}
            {% for src_subnet, dst_subnet in interface.src_subnet | zip(interface.dst_subnet) %}
            config vpn ipsec phase2-interface
            edit "{{ interface.name }}"
            set phaselname "{{ interface.name }}"
            set proposal "{{ interface.proposal | join(' ') }}"
            set dhgrp "{{ interface.dhgrp }}"
            set keylifeseconds "{{ interface.keylifeseconds }}"
            set auto-negotiate "{{ interface.auto_negotiate }}"
            set src-subnet "{{ src_subnet }}"
            set dst-subnet "{{ dst_subnet }}"
            next
            {% endfor %}
            end
            exit
            {% endfor %}
