---
- name: Backup FortiGate Firewalls
  hosts: firewalls
  gather_facts: no
  vars:
    backup_base_dir: /home/kushal/Backup/SCP_Backup/

  tasks:

    - name: Get current datetime
      set_fact:
        current_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Create backup directory for each firewall
      file:
        path: "{{ backup_base_dir }}/{{ inventory_hostname }}"
        state: directory
        mode: '0755'

    - name: Backup FortiGate configuration
      expect:
        command: "scp {{ ansible_user }}@{{ ansible_host }}:sys_config {{ backup_base_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ current_datetime }}.conf"
        responses:
          "assword:": "{{ ansible_ssh_pass }}"
        timeout: 60
      delegate_to: localhost
