---
- name: Backup FortiGate Configuration
  hosts: firewalls
  gather_facts: no
  vars:
    sftp_host: "172.23.1.102"
    sftp_user: "fwbackup"
    sftp_password: "2002"
    backup_base_path: "/upload"

  tasks:
    - name: Get current datetime
      set_fact:
        current_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

    - name: Create backup directory if it doesn't exist
      expect:
        command: sftp {{ sftp_user }}@{{ sftp_host }}
        responses:
          'password:': "{{ sftp_password }}"
          'sftp>': "mkdir {{ backup_base_path }}/{{ inventory_hostname }}"
      ignore_errors: yes

    - name: Execute backup command via SSH
      expect:
        command: ssh {{ ansible_user }}@{{ ansible_host }}
        responses:
          "password:": "{{ ansible_ssh_pass }}"
          ".*#": "execute backup full-config sftp {{ backup_base_path }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ current_datetime }}.conf 172.23.1.102:22 fwbackup 2002 "
      register: backup_result

    - name: Verify backup completion
      debug:
        msg: "Backup completed successfully for {{ inventory_hostname }}"
      when: backup_result.rc == 0

    - name: Debug backup failure
      debug:
        msg: "Backup failed for {{ inventory_hostname }}"
      when: backup_result.rc != 0
