---
- name: Configure FortiGate SD-WAN Zones and Members
  hosts: localhost
  gather_facts: no
  vars:
    fortigate_user: "your_username"
    fortigate_password: "your_password"
    fortigate_ip: "fortigate_ip_address"
    sdwan_zones:
      - name: "INTERNET_SDWAN_Test"
    
    sdwan_members:
      - id: 2
        interface: ""
        zone: "INTERNET_SDWAN_Test"
        gateway: "209.148.55.49"
      - id: 3
        interface: ""
        zone: "INTERNET_SDWAN_Test"
        gateway: "38.88.186.89"

  tasks:
    - name: SSH to FortiGate and configure SD-WAN zones
      expect:
        command: ssh "{{ fortigate_user }}@{{ fortigate_ip }}"
        responses:
          (?i)password: "{{ fortigate_password }}"
          ".*#": |
            {% for zone in sdwan_zones %}
            config vdom
            edit "root"
            config system sdwan
            config zone
            edit "{{ zone.name }}"
            next
            end
            end
            exit

    - name: SSH to FortiGate and configure SD-WAN members
      expect:
        command: ssh "{{ fortigate_user }}@{{ fortigate_ip }}"
        responses:
          (?i)password: "{{ fortigate_password }}"
          ".*#": |
            {% for member in sdwan_members %}
            config vdom
            edit "root"
            config system sdwan
            config members
            edit "{{ member.id }}"
            set interface "{{ member.interface }}"
            set zone "{{ member.zone }}"
            set gateway "{{ member.gateway }}"
            next
            end
            end
            exit
